export enum AppRoutes {
  HOME = "/",
  ABOUT = "/about",
  CATEGORIES = "/categories",
  CONTACT = "/contact",
  PRODUCTS = "/products",
  PRODUCT = "/products/:id",
  LOGIN = "/login",
  REGISTER = "/register",
  CART = "/cart",
  WISH_LIST = "/wishlist",
  CHECKOUT = "/checkout",
  BRANDS = "/brands",
  COUPONS = "/coupons",
  ORDERS = "/orders",
  SUB_CATEGORIES = "/subcategories",
  USER_PROFILE = "/profile",
  USER_ADDRESSES = "/address",
  TRACK_ORDERS = "/track-order",
}
